theme = "blowfish"
baseURL = "https://gianlu.xyz/"
languageCode = "en"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

buildDrafts = false
buildFuture = false

[imaging]
  anchor = 'Center'

[outputs]
  home = ["HTML"]
