languageCode = "en"
languageName = "English"
weight = 1
title = "devgianlu"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"

[author]
 name = "Gianluca Altomani"
 image = "img/profile_photo.jpg"
 headline = "Software Developer | IoT research | CTF player"
 links = [
   { email = "mailto:altomanigianluca@gmail.com" },
   { github = "https://github.com/devgianlu" },
   { gitlab = "https://gitlab.com/devgianlu" },
   { linkedin = "https://linkedin.com/in/devgianlu" },
   { twitter = "https://twitter.com/devgianlu" },
   { stack-overflow = "https://stackoverflow.com/users/5446197/devgianlu" },
 ]
