colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = false
enableCodeCopy = true

disableImageOptimization = true

[header]
  layout = "basic"

[footer]
  showMenu = false
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = false
  showMoreLink = false
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = false

[buymeacoffee]
  identifier = "devgianlu"
  globalWidget = true
  globalWidgetColor = "#FFDD00"
  globalWidgetPosition = "Right"
